In [1]:
import torch
import torch.optim as optim
import torch.nn as nn

class Mymodel(nn.Module) :
    def __init__(self) :
        super(Mymodel, self).__init__()
        self.Net = nn.Sequential(nn.Linear(1, 2), 
                                 nn.ReLU(), 
                                 nn.Linear(2, 1))
    def forward(self, x) :
        return self.Net(x)

x_data = torch.tensor([[1.0], [2.0], [3.0]])
y_data = torch.tensor([[2.0], [4.0], [6.0]]) 
test_data = torch.tensor([[4.0]])
    
learning_rate = 1e-2
max_epoch = 1000
model = Mymodel()
optimizer = optim.Adam(model.parameters(), lr = learning_rate)
criterion = nn.MSELoss()

for epoch in range(max_epoch) :
    model.train()
    for x, label in zip(x_data, y_data) :
        optimizer.zero_grad()
        outs = model(x)
        loss= criterion(outs, label)
        loss.backward()
        optimizer.step()
    
    model.eval()
    with torch.no_grad() :
        outs = model(test_data)
        print(outs)

tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[0.1716]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[0.2888]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[0.4140]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[0.5468]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[0.6873]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[0.8357]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[0.9921]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[1.1567]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[1.3296]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[1.5108]])
tensor([1.]) tensor([2.])
tens

tensor([3.]) tensor([6.])
tensor([[7.6310]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.6338]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.6367]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.6395]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.6423]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.6451]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.6479]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.6507]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.6535]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.6563]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tens

tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8532]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8549]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8567]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8584]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8601]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8618]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8635]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8651]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8668]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.8684]])
tensor([1.]) tensor([2.])
tens

tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9655]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9660]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9666]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9672]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9677]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9683]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9688]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9693]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9698]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9703]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tens

tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9955]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9956]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9957]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9958]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9959]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9960]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9961]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9961]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9962]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9963]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tens

tensor([3.]) tensor([6.])
tensor([[7.9996]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9996]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9996]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9996]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9996]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9997]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9997]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9997]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9997]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[7.9997]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tens

tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tens

tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tens

tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tens

tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]) tensor([2.])
tensor([2.]) tensor([4.])
tensor([3.]) tensor([6.])
tensor([[8.0000]])
tensor([1.]

tensor([3.]) tensor([6.])
tensor([[8.0000]])
